### ISSUE TITLE
how to get the tennis motion data?

### ISSUE THREAD

**Issue by JustLuoxi** [nv-tlabs/vid2player3d#4]
Hi  Haotian, 

Thanks for sharing your great work! 

I'm wondering if the tennis motion data is available now. When I trained the low-policy, I failed to run as "no such file data/motion_lib/tennis_djokovic". 

By the way, are you missing the script for training the motion embedding? 

Looking forward to your reply. Thanks!

**Comment by Haotianz94** [comment]
Unfortunately the tennis motion data is still not available due to license issues and we do not foresee the chance of releasing that data in the near future.
For training the motion embedding, you can run the script assuming the motion data is available.
`python vid2player/motion_vae/train.py --exp federer`
